core/urls.py
from django.conf.urls import url
from core.views import *
from.import views

		# from django.conf.urls import patterns, include, url

urlpatterns = [

    url(r'^$',views.index, name='index'),
    url(r'^$', index),
    url(r"^register/", CreateUser),
    url(r"^login/",login),
    url(r"^logout/",logout_view),
    url(r"^dashboard/",dashboard),
    url(r"^update/",update),
    url(r"^project/",project),
    url(r"^question/",QuestionView),
    url(r"^discussions/",Discussions),
    url(r'^answerupdate/(?P<id>[0-9]+)/$', AnswerUpdate, name='answerupdate'),
    url(r'^answerdelete/(?P<id>[0-9]+)/', AnswerDelete, name='answerdelete'),
    url(r'^questiondelete/(?P<id>[0-9]+)/', QuestionDelete, name='questiondelete'),
    url(r'^answer/', SendAnswer),
    url(r"^home/",Home),
    url(r"^signup/",Signup),
    url(r"^setting/",password),
    url(r"^questionList/",QuestionList),

    # url(r"^singleprofile/", SingleProfile),
    url(r"^menberlist/", ProfileList),
    url(r'^profiledetails/(?P<id>[0-9]+)/', ProfileDetails),
    url(r"^mailSend/", mailSend),
    url(r"^search/", Search),
    url(r"^projectslist",ProjectList),
    url(r'^projectdelete/(?P<id>[0-9]+)/', ProjectDelete, name='projectdelete'),
    url(r'^projectupdate/(?P<id>[0-9]+)/', ProjectUpdate, name='projectupdate'),

]

core/forms.py
# from django.db import models
# from django.forms import ModelForm
from django import forms
from core.models import *
from django.contrib.auth.models import User

# class UserProfileForm(forms.ModelForm):
#     class Meta:
#         model = UserProfile
#         fields = ['gender', 'age']
#
# class UserForm(forms.ModelForm):
#     class Meta:
#         model = User
#         fields = ['first_name', 'last_name', 'email', 'username']


class AllForm(forms.Form):
    GENDER_CHOICES = (("M", "Male"), ("F", "Female"))

    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)
    gender = forms.ChoiceField(choices=GENDER_CHOICES)
    email = forms.EmailField()
    password = forms.CharField(max_length='15',widget=forms.PasswordInput())
    confirm_password = forms.CharField(max_length='15', widget=forms.PasswordInput())

class LoginForm(forms.Form):
      email=forms.EmailField()
      password = forms.CharField(max_length='15', widget=forms.PasswordInput())
class Register (forms.Form) :
       email = forms.EmailField()
       dipp = forms.CharField(max_length="15")
       companyName = forms.CharField(max_length=100,required=False)
       designatePerson = forms.CharField(max_length=50,required=False)
       founderCofounder = forms.CharField(max_length=50,required=False)
       website = forms.CharField(max_length=50,required=False)
       mobile = forms.IntegerField(required=False)
       address = forms.CharField(max_length=256,required=False)
       city = forms.CharField(max_length=25,required=False)
       state = forms.CharField(max_length=30,required=False)
       pincode = forms.IntegerField(required=False)
       facebook = forms.CharField(max_length=256,required=False)
       linkedin = forms.CharField(max_length=256,required=False)
       twitter = forms.CharField(max_length=256,required=False)
       profileImage=forms.ImageField(label='Select a file', help_text='max. 2 megabytes',required=False)
       INDUSTRY_TYPE = (("Healthcare", "Healthcare"), ("FinTech", "FinTech"),
                       ("Logistics", "Logistics"))
       industry = forms.ChoiceField(choices=INDUSTRY_TYPE,required=False)
       password = forms.CharField(max_length='15', widget=forms.PasswordInput(),required=False)
       provideSupport=forms.CharField(max_length=300,required=False)
       needSupport=forms.CharField(max_length=300,required=False)
       PROFILE_TYPE = (("Startup Companies", "Startup Companies"), ("Mentors/Consultants", "Mentors/Consultants"),
                        ("Investors(Angels/VC Funds)", "Investors(Angels/VC Funds)"), ("Accelerators", "Accelerators")
                        , ("Incubators", "Incubators"), ("Event Manager", "Event Manager"))
       profileType = forms.ChoiceField(choices=PROFILE_TYPE,required=False)


class ProjectForm(forms.Form):
    companyName = forms.CharField(max_length=100)
    brandName = forms.CharField(max_length=100)
    BUSINESS_TYPE = (("B2B", "B2B"), ("B2C", "B2C"), ("C2B", "C2B"), ("B2B2C", "B2B2C"))
    typeOfBusiness = forms.ChoiceField(choices=BUSINESS_TYPE)
    url = forms.CharField(max_length=100)
    description = forms.CharField(max_length=300)
    logo = forms.ImageField(label='Select a file', help_text='max. 2 megabytes')
    videoLink = forms.CharField(max_length=256)
    aboutProductCompany = forms.FileField(label='Select a file', help_text='max. 2 megabytes')
    investor = forms.ImageField(label='Select a file', help_text='max. 2 megabytes')

class QuestionForm(forms.Form):
    # group = forms.ModelChoiceField(queryset=Group.objects.all())
    # category = forms.ModelChoiceField(queryset=Category.objects.filter(group=group.id)) // error is here

    # QUESTION_CATEGORY = (
    # ("Category1", "Category1"), ("Category2", "Category2"), ("Category3", "Category3"), ("Category4", "Category4"))
    # category = forms.ChoiceField(choices=QUESTION_CATEGORY)
    # SUB_CATEGORY = (
    #     ("SubCategory1", "SubCategory1"), ("SubCategory2", "SubCategory2"), ("SubCategory3", "SubCategory3"),
    #     ("SubCategory4", "SubCategory4"))
    # subcategory = forms.ChoiceField(choices=SUB_CATEGORY)

    question=forms.CharField(max_length=1000)

core/templates/Searcherror.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}

    <!--///////////////////////////////////////////////////////////////////////////////////
                                      Member profile Section
    ///////////////////////////////////////////////////////////////////////////////////-->
    <section id="question-paper-list">
        <div class="container">
         <div class="box -color-light -border-gray">
  <div class="search-no-results">
    <div>
      <i class="e-icon -icon-cactus -size-enormous"></i>
    </div>
    <div>
      <h2 class="t-heading -size-xs">
           0 results       </h2>
      <p class="t-body">
     Your search returned no matches.

      </p>
    </div>
  </div>
</div>
        </div>
    </section>











{% endblock %}

core/templates/UserQuestionList.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}

<!--///////////////////////////////////////////////////////////////////////////////////
                                  Member profile Section
///////////////////////////////////////////////////////////////////////////////////-->

<section class="dashboard-update">
    <div class="container">
        <br>
        <nav id="site-navigation" class="main-navigation" role="navigation">
            <div class="nav-menu">
                <ul>
                    <li class="current_page_item active"><a href="/dashboard/" title="Home">Dashboard</a></li>
                    <li class="page_item page-item-7"><a href="/setting/">Setting</a></li>

                    <li class="page_item page-item-9"><a href="/project/">Add Project</a></li>
                    <li class="page_item page-item-9"><a href="/question/">Add Question</a></li>
                    <li class="page_item page-item-9"><a href="/questionList/">Question</a></li>
                    <li class="page_item page-item-9"><a href="/projectslist/">Manage Projects</a></li>


                </ul>
            </div><!-- .nav-menu -->
        </nav><!-- #site-navigation -->

    </div>
</section>


<div id="question-paper-list" class="m-b-30">
    <div class="container">
                    {{msg}}
        <div class="row">
            <div class="col-md-12">
                <div class="card-profile bg-darkgreen">
                    <div class="row">
                       <div class="col-md-10">
                           <p class="p-heading f-w">
                               Topic

                           </p>
                       </div><!-- 
                        <div class="col-md-3">
                            <p class="p-heading f-w">
                                Replies

                            </p>
                        </div> -->
                        <div class="col-md-2">
                            <p class="p-heading f-w">
                                Delete

                            </p>
                        </div>

                    </div> <!--first card end-->




            </div>
                <div class="card-profile">
<!--                     {{questionData.question }}
 -->                    {% for data in questionData %}
                    <div class="row">
                        <div class="col-md-10">
                            <p class="p-heading f-green">
                          {{ data.question }}

                            </p>
                        </div><!-- 
                        <div class="col-md-3">
                            <p class="p-heading f-or">
                               27

                            </p>
                        </div> -->

                        <div class="col-md-2">

                            <div class="row">
                                <div class="col-xs-3">
                                <a href="/questiondelete/{{data.id}}">Delete</a>

<!--                                     <img src="{{data.profileImage}}" width="100%">
 -->                                </div>
                                
                            </div>
                        </div>

                    </div> <!--first row end-->
                    <hr style="border-color:#e8e8e8;">
                     {% endfor %}




                </div>



        </div>
    </div>

    </div>
</div>















{% endblock %}

core/templates/dashboard-setting.html
{% extends "base.html" %}
{% block content %}
<!--///////////////////////////////////////////////////////////////////////////////////
                                  Sign up Section
///////////////////////////////////////////////////////////////////////////////////-->

<section class="dashboard-update">
    <div class="container">
        <br>
        <nav id="site-navigation" class="main-navigation" role="navigation">
            <div class="nav-menu">
                <ul>
                    <li class="current_page_item"><a href="/dashboard/" title="Home">Dashboard</a></li>
                    <li class="page_item page-item-7 active"><a href="/setting/">Setting</a></li>
                    <li class="page_item page-item-9"><a href="/project/">Add Project</a></li>
                    <li class="page_item page-item-9"><a href="/question/">Add Question</a></li>
                    <li class="page_item page-item-9"><a href="/questionList/">Question</a></li>
                    <li class="page_item page-item-9"><a href="/projectslist/">Manage Projects</a></li>

                </ul>
            </div><!-- .nav-menu -->
        </nav><!-- #site-navigation -->

    </div>
</section>

<div id="member-profile-section">

    <div class="container">
        <form name="form" method="post" action="/pwd/">



        <div class="row">
            <div class="col-md-12">
                <div class="card-profile">
                    <label class="f-or">CHANGE PASSWORD</label>


                    <div class="form-group">
                        <label class="p-heading"  for="oldpass"> Old Password</label>
                        <input type="password" name="oldPassword" class="form-control" id="oldpass" placeholder="Enter your Current Password">
                    </div>

                    <div class="form-group">
                        <label class="p-heading"  for="newpass">New Password</label>
                        <input type="password" name="newPassword" class="form-control" id="newpass" placeholder="Enter your New Password">
                    </div>

                    <div class="form-group">
                        <label class="p-heading"  for="confirmpass">Confirm Your Password</label>
                        <input type="password" name="confPassword" class="form-control" id="confirmpass" placeholder="Re-Enter Your Password">
                    </div>

                </div>
            </div>
        </div>


        <br>
        <div class="row">
            <div class="col-md-12 text-center">
                <button type="submit" class="btn btn-primary btn-lg bg-or">Submit</button>
            </div>
        </div>
        </form>

    </div>




</div>
<br>



{% endblock %}

core/templates/invoice.htm
<!DOCTYPE html>
<!-- saved from url=(0040)file:///Users/user/Pictures/invoice.html -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <title>{{title}}</title>

    <style>
    .invoice-box{
        max-width:800px;
        margin:auto;
        padding:30px;
        border:1px solid #eee;
        box-shadow:0 0 10px rgba(0, 0, 0, .15);
        font-size:16px;
        line-height:24px;
        font-family:'Helvetica Neue', 'Helvetica', Helvetica, Arial, sans-serif;
        color:#555;
    }

    .invoice-box table{
        width:100%;
        line-height:inherit;
        text-align:left;
    }

    .invoice-box table td{
        padding:5px;
        vertical-align:top;
    }

    .invoice-box table tr td:nth-child(2){
        text-align:right;
    }

    .invoice-box table tr.top table td{
        padding-bottom:20px;
    }

    .invoice-box table tr.top table td.title{
        font-size:45px;
        line-height:45px;
        color:#333;
    }

    .invoice-box table tr.information table td{
        padding-bottom:40px;
    }

    .invoice-box table tr.heading td{
        background:#eee;
        border-bottom:1px solid #ddd;
        font-weight:bold;
    }

    .invoice-box table tr.details td{
        padding-bottom:20px;
    }

    .invoice-box table tr.item td{
        border-bottom:1px solid #eee;
    }

    .invoice-box table tr.item.last td{
        border-bottom:none;
    }

    .invoice-box table tr.total td:nth-child(2){
        border-top:2px solid #eee;
        font-weight:bold;
    }

    @media only screen and (max-width: 600px) {
        .invoice-box table tr.top table td{
            width:100%;
            display:block;
            text-align:center;
        }

        .invoice-box table tr.information table td{
            width:100%;
            display:block;
            text-align:center;
        }
    }
    </style>
</head>

<body>
    <div class="invoice-box">
        
            {% for it in item %}
              
            {% endfor %}
            {% if booking.is_gift==True %}
              
            {% endif %}
              <table cellpadding="0" cellspacing="0">
            <tbody><tr class="top">
                <td colspan="2">
                    <table>
                        <tbody><tr>
                            <td class="title">
                                <img src="./invoice_files/logo.png" style="width:100%; max-width:150px;">
                            </td>
                            <td>
                                Invoice #: {{booking.id}}<br>
                                Created: {{booking.placed_on.strftime('%d %b, %Y')}}<br>
                            </td>
                        </tr>
                    </tbody></table>
                </td>
            </tr>

            <tr class="information">
                <td colspan="2">
                    <table>
                        <tbody><tr>
                            <td>
                                {{booking.shipping_address1}} {{booking.shipping_address2}}<br>
                                {{booking.shipping_city}} ({{booking.shipping_state}})<br>
                                {{booking.shipping_pincode}}
                            </td>

                            <td>
                                {{booking.shipping_name}}<br>
                                {{booking.shipping_phone}}<br>
                                {{request.user.email}}
                            </td>
                        </tr>
                    </tbody></table>
                </td>
            </tr>

            <tr class="heading">
                <td>
                    Payment Method
                </td>

                <td>
                    {{booking.get_payment_type_display()}} #
                </td>
            </tr>

            <tr class="heading">
                <td>
                    Item
                </td>
                <td>
                    Price
                </td>
            </tr><tr class="item">
                  <td>
                      {{it.plant.name}}<br>
                      Quantity: {{it.quantity}}
                  </td>

                  <td>
                      ₹ {{it.quantity*it.price}}
                  </td>
              </tr><tr class="item">
                  <td>
                      Gift Wrap
                  </td>

                  <td>
                      ₹ 25
                  </td>
              </tr><tr class="item">
                  <td>
                      Coupon Discount
                  </td>
                  <td>
                      ₹ {{booking.coupon_discount}}
                  </td>
              </tr>

              <tr class="item">
                  <td>
                      Dilivery Charge
                  </td>
                  <td>
                      ₹ {{booking.delivery_charge}}
                  </td>
              </tr>



            <tr class="total">
                <td></td>
                <td>
                   Total: ₹ {{booking.amount}}
                </td>
            </tr>
        </tbody></table>
    </div>


</body></html>

core/templates/login.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'css/login.css' %}">

<!--///////////////////////////////////////////////////////////////////////////////////
                                  Sign up Section
///////////////////////////////////////////////////////////////////////////////////-->



<section id="signup-section">
    <div class="container">
        <br>

        <div class="row">


            <div class="col-md-6  p-0 hidden-xs">


                <div class="login-bg">

                </div>



            </div>



            <div class="col-md-6 p-0">


                    <div class="form-contain-login">
                        <div class="form-contain-element">
                        <h2>Login</h2>
                        <p>Synth polaroid bitters chillwave pickled. Vegan disrupt tousled.</p>

                        <form  action="/login/" name="login-form" id="girisyap" id="sidebar-user-login" method="post" >
                                 {% csrf_token %}

                            <div class="form-group">
                                <label class="control-label" for="inputNormal">Username</label>
                                <br>
                                <input type="text" name="email" class="bp-suggestions form-control" cols="50" rows="10" ></input>
                            </div>
                            <div class="form-group soninpt">
                                <label class="control-label" for="inputNormal">Password</label>
                                <br>
                                <input type="password" name="password" class="bp-suggestions form-control" cols="50" rows="10"></input>
                            </div>
                            <input type="submit" value="Login" class="girisbtn" tabindex="100" />
                        </form>
                        {{msg}}
                       <!-- <button id="moveleft">Sign Up</button>-->
                    </div>


                    </div>
        </div>
        </div>


                </div>




</section>




    <!--Email:       {{login_form.email}}<br>-->
    <!--Password:     {{login_form.password}}<br>-->
     <!--<input type="submit" VALUE="Submit">-->
<!--</form>-->

<!--{{msg}}-->



{% endblock %}

core/templates/projectUpdate.html
{% extends "base.html" %}
{% block content %}


<!--///////////////////////////////////////////////////////////////////////////////////
                                  Sign up Section
///////////////////////////////////////////////////////////////////////////////////-->

<section class="dashboard-update">
    <div class="container">
        <br>
        <nav id="site-navigation" class="main-navigation" role="navigation">
            <div class="nav-menu">
                <ul>
                    <li class="current_page_item"><a href="/dashboard/" title="Home">Dashboard</a></li>
                    <li class="page_item page-item-7"><a href="/setting/">Setting</a></li>

                    <li class="page_item page-item-9 active"><a href="/project/">Add Project</a></li>
                    <li class="page_item page-item-9"><a href="/question/">Add Question</a></li>
                    <li class="page_item page-item-9"><a href="/questionList/">Question</a></li>
                    <li class="page_item page-item-9"><a href="/projectslist/">Manage Projects</a></li>

                </ul>
            </div><!-- .nav-menu -->
        </nav><!-- #site-navigation -->

    </div>
</section>

<div id="member-profile-section">

 <div class="container">
     <samp class="text-center">{{msg}}</samp>
 <div class="card-profile">
                    <label class="f-or"> Project / Works</label>


  <form action="/projectupdate/{{ projectForm.id }}" method="post" id="register-form" enctype="multipart/form-data" onsubmit="return formValidation()">
      {% csrf_token %}

                <div class="form-group">
                    <label class="p-heading"  for="name1">  Name </label>
                  {{projectForm.companyName}}
                    <!--<input type="text" name="projectname" class="form-control" id="name1" placeholder="Email" >-->
                </div>

                <div class="form-group">
                    <label class="p-heading"  for="brandname"> Brand Name</label>
                    {{projectForm.brandName}}
                    <!--<input type="text" name="projectbrandname" class="form-control" id="brandname" placeholder="Email">-->
                </div>

                    <div class="row">
                        <div class="col-md-6">
                <div class="form-group">
                    <label class="p-heading"  for="business1"> Type of Business</label>
                    {{projectForm.typeOfBusiness}}
                    <!--<select class="form-control" id="business1" name="projectbusiness">-->
                        <!--<option>B2B</option>-->
                        <!--<option>B2C</option>-->
                        <!--<option>C2B</option>-->
                        <!--<option>B2B2C</option>-->

                    <!--</select>-->
                </div>
                        </div>

                        <div class="col-md-6">

                <div class="form-group">
                    <label class="p-heading"  for="url1">URL link</label>
                    {{projectForm.url}}
               <div id="id_urlError"></div>

                    <!--<input type="text" name="projecturl" class="form-control" id="url1" placeholder="Email">-->
                </div>

                        </div>
                    </div>

                <div class="form-group">
                    <label class="p-heading">  Brief Description </label>
                     {{projectForm.description}}

              <div id="id_descriptionError"></div>
                    <!--<textarea class="form-control" name="projectdescription" id="description" placeholer="Brief Description">-->
                                      <!--</textarea>-->
                </div>


                <div class="form-group">
                    <label class="p-heading"  for="videolink"> Video Link to embed</label>
                    {{projectForm.videoLink}}
                    <!--<input type="text"  name="projectvideolink" class="form-control" id="videolink" placeholder="Video Link">-->
                </div>

                    <div class="row">
                        <div class="col-md-12">

                                    <div class="form-group">

                                        <div class="form-group">
                                            <label class="p-heading"> Investor Deck</label>
                                            {{projectForm.investor}}
                                            <!--<input type="file" id="investor" name="projectinvestor">-->

                                        </div>
                                    </div>

                             <div class="form-group">

                        <div class="form-group">
                            <label class="p-heading"> Logo / Image</label>
                            {{projectForm.logo}}
                          <div id="id_logoError"></div>
                            <!--<input type="file" id="logo" name="projectlogo">-->

                        </div>
                    </div>


                <div class="form-group">
                    <label class="p-heading"  for="aboutc"> About the product/ company</label>
                    {{projectForm.aboutProductCompany}}
                    <!--<input type="text" name="projectaboutc" class="form-control" id="aboutc" placeholder=" About the product / company">-->
                </div>

                        </div>



                    </div>


           <br>
<div class="row">
    <div class="col-md-12 text-center">
            <button type="submit"  class="btn btn-primary btn-lg bg-or">Submit</button>
</div>
</div>
            </form>
{{msg}}

</div>




</div>
</div>
<br>


<script type='text/javascript'>
$(document).ready(function(){


 $('input[type="text"]').addClass('form-control');
 $('input[type="number"]').addClass('form-control');
 //$('input[type="file"]').addClass('form-control');
 $('select').addClass('form-control');
    $("#id_companyName").attr('readonly','readonly');


});
</script>

<script type="text/javascript">
    
function formValidation(obj) {
    {#    alert();45#}

    var id_url = document.getElementById('id_url').value;
    var id_description = document.getElementById('id_description').value;
    var id_logo = document.getElementById('id_logo').value;
    {#alert(45);#}
    if (id_url !== "") {

        if (id_description !== "") {
            if (id_logo !== "") {

                return true;

            } else {

                document.getElementById("id_logoError").innerHTML = "<span style='color:red;'>Please file in this field. </span>";
                document.getElementById("id_descriptionError").remove();
                return false;

            }

        } else {
            document.getElementById("id_descriptionError").innerHTML = "<span style='color:red;'>Please file in this field. </span>";
            document.getElementById("id_urlError").remove();
            return false;

        }

    } else {
        document.getElementById("id_urlError").innerHTML = "<span style='color:red;'>Please file in this field. </span>";
        // document.getElementById("id_mobileError").remove();
        return false;

    }


}

</script>


{% endblock %}

core/templates/questionList.html
{% extends "base.html" %}
{% block content %}
{% load staticfiles %}

<!--///////////////////////////////////////////////////////////////////////////////////
                                  Member profile Section
///////////////////////////////////////////////////////////////////////////////////-->

<section id="question-paper-list">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card-profile bg-darkgreen">
                    <div class="row">
                       <div class="col-md-5">
                           <p class="p-heading f-w">
                               Topic

                           </p>
                       </div>
                        <div class="col-md-3">
                            <p class="p-heading f-w">
                                Replies

                            </p>
                        </div>
                        <div class="col-md-4">
                            <p class="p-heading f-w">
                                Last Post

                            </p>
                        </div>

                    </div> <!--first card end-->



            </div>
                <div class="card-profile">
<!--                     {{questionData.question }}
 -->                    {% for data in questionData %}
                    <div class="row">
                        <div class="col-md-5">
                            <p class="p-heading f-green">
                          {{ data.question }}

                            </p>
                        </div>
                        <div class="col-md-3">
                            <p class="p-heading f-or">
                               27

                            </p>
                        </div>

                        <div class="col-md-4">

                            <div class="row">
                                <div class="col-xs-3">
                                    <img src="{{data.profileImage}}" width="100%">
                                </div>
                                <div class="col-xs-9">
                                    <p class="p-heading">
                                        {{data.profileName}}

                                    </p>
                                </div>
                            </div>
                        </div>

                    </div> <!--first row end-->
                    <hr style="border-color:#e8e8e8;">
                     {% endfor %}




                </div>



        </div>
    </div>

    </div>
</section>




    <!--///////////////////////////////////////////////////////////////////////////////////
                                      Member profile Section
    ///////////////////////////////////////////////////////////////////////////////////-->
    <!--<section id="question-paper-list">-->
        <!--<div class="container">-->
            <!--<br>-->
              <!--{{questionData.question }}-->

              <!--{% for data in questionData %}-->
                <!--<div class="card-profile m-b-30">-->
                    <!--<div class="row p-30">-->
                        <!--<div class="col-md-2 text-center">-->
                            <!--<img src="{% static 'img/test.png' %}" width="60%">-->
                            <!--<p class="p-heading f-green f-20"> Lorem Ipsum</p>-->
                        <!--</div>-->
                        <!--<div class="col-md-10">-->
                            <!--<p class="f-30 f-green"> {{ data.question }}</p>-->
                            <!--<p class="f-16"> {{ data.question }}</p>-->

                        <!--</div>-->



                    <!--</div> &lt;!&ndash;first card end&ndash;&gt;-->




                <!--</div>-->


            <!--{% endfor %}-->

        <!--</div>-->
    <!--</section>-->











{% endblock %}